rvm:
  - "1.9.3"
services:
  - couchdb
notifications:
  email: false
before_script:
  - "/bin/bash test/setup_couch.sh"
  - "bundle exec bin/tapicero start test/config.yaml"
  - "cat /tmp/test-tapicero.log"
