#
# Default configuration options for Tapicero
#

#
# Database
#
users_db_name: "users"
db_prefix: "user-"
couch_connection:
  protocol: "http"
  host: "localhost"
  port: 5984
  username: ~
  password: ~
  prefix: ""
  suffix: ""
  join: "_"
